"""Implementation of Stochastically Stable Distribution (SSD) analysis.

This module implements the SSD algorithm for computing stochastically stable
distributions of perturbed Markov processes, with applications to evolutionary
game theory and multiagent learning.

Based on:
"An Algorithm for Computing Stochastically Stable Distributions with
Applications to Multiagent Learning in Repeated Games"
by John R. Wicks and Amy Greenwald.
https://arxiv.org/pdf/1207.1424
"""

from numbers import Number
from collections import defaultdict
from typing import Any, Dict, List, Optional, Tuple, Union
import warnings

import numpy as np
from numpy.polynomial import Polynomial as P
import scipy.sparse as sp
import scipy.sparse.linalg as spla

from open_spiel.python.egt import utils
from open_spiel.python.egt import alpharank


class Graph(object):
  """Implementation of Kosaraju's algorithm for computing communicating classes of a
  directed graph, expressed as an adjacency matrix. Taken from
  http://www.kylesauri.com/home/kosarajus-algorithm-in-python-3.
  Some methods are implemented in a non-recursive way to avoid recursion limit.
  """

  def __init__(self, mat, zeroTest):
    """Takes an adjacency matrix and prepares for computing its communicating
    and closed classes.
    """
    s = mat.shape
    self.dim = s[0]
    assert (self.dim == s[1] and len(s) == 2)
    self.zeroTest = zeroTest
    self.mat = mat
    self.is_sparse = sp.issparse(mat)
    self.communicatingClasses = None
    self.closedClasses = None

  def Visit(self, vertex):
    """Performs a depth-first search of the graph starting
    from the given node/vertex to compute a list of
    sortedVertices consistent with the pre-order generated by
    adjacency, keeping track of progress via the list of
    visited vertices.
    """

    if vertex in self.visited:
      return
    visited_set = set(self.visited)

    stack = [(vertex, False)]
    while stack:
      v, processed = stack.pop()

      if processed:
        self.sortedVertices.insert(0, v)
        continue

      if v in visited_set:
        continue

      self.visited.append(v)
      visited_set.add(v)
      stack.append((v, True))

      if self.is_sparse:
        col = self.mat.getcol(v)
        nbrs = col.nonzero()[0]
        for neighbor in sorted(nbrs, reverse=True):
          if neighbor in visited_set:
            continue
          val = self.mat[neighbor, v]
          if not self.zeroTest(val):
            stack.append((neighbor, False))
      else:
        for neighbor in range(self.dim - 1, -1, -1):
          if not self.zeroTest(self.mat[neighbor, v]) and neighbor not in visited_set:
            stack.append((neighbor, False))

  def Assign(self, vertex, root):
    """Associate a vertex with its communicating class representative, root,
    via the components dictionary.
    """
    stack = [vertex]
    while stack:
      v = stack.pop()
      if v in self.components:
        continue
      self.components[v] = root
      if self.is_sparse:
        row = self.mat.getrow(v)
        nbrs = row.nonzero()[1]
        for neighbor in nbrs:
          if neighbor in self.components:
            continue
          val = self.mat[v, neighbor]
          if not self.zeroTest(val):
            stack.append(neighbor)
      else:
        for neighbor in range(self.dim):
          if not self.zeroTest(self.mat[v, neighbor]) and neighbor not in self.components:
            stack.append(neighbor)

  def CommunicatingClasses(self):
    """Apply Kosaraju's algorithm to compute the set of communicating classes,
    espressed as a dictionary of representatives from each class with the
    associate values given by the classes, as arrays.
    """

    if (self.communicatingClasses):
      return self.communicatingClasses

    self.visited = []
    self.sortedVertices = []
    self.components = {}

    for vertex in range(self.dim):
      self.Visit(vertex)

    for vertex in self.sortedVertices:
      self.Assign(vertex, vertex)

    self.communicatingClasses = {}
    for vertex in range(self.dim):
      root = self.components[vertex]
      if root in self.communicatingClasses:
        self.communicatingClasses[root].append(vertex)
      else:
        self.communicatingClasses[root] = [vertex]

    return self.communicatingClasses

  def ClosedClasses(self):

    if (self.closedClasses):
      return self.closedClasses

    if (not self.communicatingClasses):
      self.communicatingClasses = self.CommunicatingClasses()

    self.closedClasses = {}
    for cc in self.communicatingClasses.keys():

      # Assume that it is closed for now
      self.closedClasses[cc] = self.communicatingClasses[cc]
      for source in self.communicatingClasses[cc]:
        if self.is_sparse:
          col = self.mat.getcol(source)
          nbrs = col.nonzero()[0]
          outside_found = False
          for target in nbrs:
            if target in self.communicatingClasses[cc]:
              continue
            val = self.mat[target, source]
            if not self.zeroTest(val):
              outside_found = True
              break
          if outside_found:
            self.closedClasses.pop(cc)
            break
        else:
          for target in range(self.dim):
            if target not in self.communicatingClasses[cc] and \
                    not self.zeroTest(self.mat[target, source]):
              self.closedClasses.pop(cc)
              break

          if cc not in self.closedClasses:
            break

    return self.closedClasses


class SparseLinearPolyMatrix(object):
  """Sparse matrix for linear polynomials a0 + a1 * epsilon.

  Stores separate sparse matrices for constant and epsilon coefficients.
  """

  __slots__ = ("shape", "_constant", "_epsilon")

  def __init__(self,
               shape: Tuple[int, int],
               constant: Optional[sp.spmatrix] = None,
               epsilon: Optional[sp.spmatrix] = None):
    self.shape = shape
    self._constant = _to_dok(constant, shape, "constant")
    self._epsilon = _to_dok(epsilon, shape, "epsilon")

  def copy(self):
    return SparseLinearPolyMatrix(self.shape,
                                  self._constant.copy(),
                                  self._epsilon.copy())

  def _iter_keys(self):
    return set(self._constant.keys()) | set(self._epsilon.keys())

  def get(self, key: Tuple[int, int], default: Any = None) -> Any:
    row, col = key
    c0 = float(self._constant.get((row, col), 0.0))
    c1 = float(self._epsilon.get((row, col), 0.0))
    if default is None:
      default = _POLY_ZERO
    if abs(c0) <= 1e-16 and abs(c1) <= 1e-16:
      return default
    if abs(c1) <= 1e-16:
      return np.poly1d([c0])
    return np.poly1d([c1, c0])

  def set(self, row: int, col: int, value: Any, tol: float = 1e-16):
    c0, c1 = _split_linear_coeffs(value, tol)
    if abs(c0) <= tol:
      self._constant.pop((row, col), None)
    else:
      self._constant[row, col] = c0
    if abs(c1) <= tol:
      self._epsilon.pop((row, col), None)
    else:
      self._epsilon[row, col] = c1

  def eliminate_zeros(self, tol: float = 1e-16):
    """Remove explicit zero entries from both sparse coefficient matrices."""
    for key in list(self._constant.keys()):
      if abs(float(self._constant.get(key, 0.0))) <= tol:
        self._constant.pop(key, None)
    for key in list(self._epsilon.keys()):
      if abs(float(self._epsilon.get(key, 0.0))) <= tol:
        self._epsilon.pop(key, None)
    return self

  def items(self):
    for key in self._iter_keys():
      value = self.get(key)
      if not _poly_zero_test(value):
        yield key, value

  def values(self):
    for _, value in self.items():
      yield value

  def nnz(self) -> int:
    return len(self._iter_keys())

  def evaluate(self, eps_value: float) -> sp.csr_matrix:
    if eps_value == 0.0:
      return _eliminate_sparse_zeros(self._constant.tocsr())
    return _eliminate_sparse_zeros(
        (self._constant + eps_value * self._epsilon).tocsr())

  @property
  def constant(self) -> sp.spmatrix:
    return self._constant

  @property
  def epsilon(self) -> sp.spmatrix:
    return self._epsilon

  def __getitem__(self, key: Tuple[int, int]) -> Any:
    if isinstance(key, tuple) and len(key) == 2:
      return self.get((key[0], key[1]), _POLY_ZERO)
    raise TypeError("SparseLinearPolyMatrix can get 2d index only")

  def __setitem__(self, key: Tuple[int, int], value: Any):
    if isinstance(key, tuple) and len(key) == 2:
      self.set(key[0], key[1], value)
      return
    raise TypeError("SparseLinearPolyMatrix can set 2d index only")


  def __mul__(self, other):
    """Scalar multiplication: self * scalar."""
    if isinstance(other, Number):
      result = SparseLinearPolyMatrix(self.shape)
      for (row, col), value in self.items():
        result.set(row, col, _ensure_poly1d(value) * float(other))
      return result
    return NotImplemented

  def __rmul__(self, other):
    """Scalar multiplication: scalar * self."""
    if isinstance(other, Number):
      return self.__mul__(other)
    return NotImplemented

  def __neg__(self):
    """Unary negation: -self."""
    return self.__mul__(-1.0)

  def __matmul__(self, other):
    """Matrix multiply: self @ other.

    ``other`` may be another SparseLinearPolyMatrix **or** a dense
    ``np.ndarray`` (numeric, 1-D or 2-D).
    """
    if isinstance(other, SparseLinearPolyMatrix):
      return _sparse_linear_matmul(self, other)
    if isinstance(other, np.ndarray):
      if other.ndim == 1:
        return self._matvec(other)
      return _sparse_linear_right_dense_mul(self, other)
    return NotImplemented

  def _matvec(self, vec: np.ndarray) -> np.ndarray:
    """Multiply self (m x k) by a 1-D vector (k,) -> (m,)."""
    m, k = self.shape
    if vec.shape[0] != k:
      raise ValueError("Shape mismatch in _matvec")
    result = np.zeros(m, dtype=object)
    for (row, col), value in self.items():
      result[row] = result[row] + _ensure_poly1d(value) * vec[col]
    return result

  def __rmatmul__(self, other):
    """Matrix multiply: other @ self (other is dense np.ndarray)."""
    if isinstance(other, np.ndarray):
      return _dense_left_sparse_linear_mul(other, self)
    return NotImplemented

  def __sub__(self, other):
    """Element-wise subtraction: self - other (both SparseLinearPolyMatrix)."""
    if not isinstance(other, SparseLinearPolyMatrix):
      return NotImplemented
    if self.shape != other.shape:
      raise ValueError("Shape mismatch in __sub__")
    result = self.copy()
    for (r, c), v in other.items():
      current = result.get((r, c), _POLY_ZERO)
      result.set(r, c, _poly_sub(current, v))
    return result


def _to_dok(matrix: Optional[sp.spmatrix],
            shape: Tuple[int, int],
            label: str) -> sp.dok_matrix:
  if matrix is None:
    return sp.dok_matrix(shape, dtype=float)
  if not sp.issparse(matrix):
    matrix = sp.coo_matrix(matrix, shape=shape, dtype=float)
  if matrix.shape != shape:
    raise ValueError(f"{label} matrix shape {matrix.shape} does not match {shape}")
  return _eliminate_sparse_zeros(matrix.todok())


def _split_linear_coeffs(value: Any, tol: float = 1e-16) -> Tuple[float, float]:
  if isinstance(value, np.poly1d):
    coeffs = value.coeffs
    degree = len(coeffs) - 1
    if degree > 1:
      return float(coeffs[-1]), float(coeffs[-2])
    if degree == 1:
      return float(coeffs[1]), float(coeffs[0])
    return float(coeffs[0]), 0.0

  if isinstance(value, Number):
    return float(value), 0.0

  try:
    arr = np.asarray(value, dtype=float)
    if arr.size == 0:
      return 0.0, 0.0
    if arr.size == 1:
      return float(arr.item()), 0.0
    if arr.size == 2:
      # (a0, a1)
      return float(arr[0]), float(arr[1])
  except Exception:
    pass

  raise TypeError("Unsupported value type for SparseLinearPolyMatrix")


def _convert_alpharank_to_ssd_format(
        payoff_tables: List[Any],
        payoffs_are_hpt_format: bool) -> Dict[str, Any]:
  """Converts Alpha-Rank payoff tables to SSD format."""
  num_strats = utils.get_num_strats_per_population(payoff_tables,
                                                   payoffs_are_hpt_format)
  if payoffs_are_hpt_format:
    num_profiles = len(payoff_tables[0])
  elif len(payoff_tables) == 1:
    num_profiles = payoff_tables[0].shape[0]
  else:
    num_profiles = utils.get_num_profiles(
        [table.shape[0] for table in payoff_tables])
  return {
    "payoff_tables": payoff_tables,
    "payoffs_are_hpt_format": payoffs_are_hpt_format,
    "num_populations": len(payoff_tables),
    "num_strats_per_population": num_strats,
    "num_profiles": num_profiles,
  }


def _validate_ssd_distribution(distribution: np.ndarray,
                               tolerance: float = 1e-6) -> bool:
  distribution = np.asarray(distribution, dtype=float)
  return (np.all(np.isfinite(distribution)) and
    np.all(distribution >= -tolerance) and
          abs(np.sum(distribution) - 1.0) <= tolerance)


def normalize(vector: Union[np.ndarray, sp.spmatrix]) -> np.ndarray:
  """Normalize a vector so that it sums to 1."""
  if sp.issparse(vector):
    arr = np.array(vector.toarray(), dtype=float).flatten()
  else:
    arr = np.array(vector, dtype=float).flatten()
  # guard against NaN/Inf values
  arr = np.nan_to_num(arr, nan=0.0, posinf=0.0, neginf=0.0)
  arr[arr < 0.0] = 0.0
  total = np.sum(arr)
  if not np.isfinite(total) or total <= 0.0:
    if arr.size == 0:
      return arr
    return np.ones_like(arr) / float(arr.size)
  return arr / total


def _select_stationary_vector(eigenvalues, eigenvectors):
  """Select eigenvector associated with the largest real eigenvalue."""
  eigenvalues = np.asarray(eigenvalues)
  idx = np.argmax(np.real(eigenvalues))
  vec = np.real(eigenvectors[:, idx])
  return vec


def _stable_distribution(matrix, tol: float = 1e-9):
  """Computes the normalized eigenvector for eigenvalue 1 for a unichain Markov matrix."""
  is_sparse = sp.issparse(matrix)
  if is_sparse:
    row_sums = np.asarray(matrix.sum(axis=1)).reshape(-1)
    col_sums = np.asarray(matrix.sum(axis=0)).reshape(-1)
    target_dense = None
  else:
    target_dense = np.asarray(matrix, dtype=float)
    row_sums = target_dense.sum(axis=1)
    col_sums = target_dense.sum(axis=0)

  rows_stochastic = np.allclose(row_sums, 1.0, atol=tol)
  cols_stochastic = np.allclose(col_sums, 1.0, atol=tol)

  use_transpose = True
  if cols_stochastic:
    use_transpose = False
  elif rows_stochastic:
    use_transpose = True

  if is_sparse:
    target_matrix = matrix.T if use_transpose else matrix
    n = target_matrix.shape[0]
    if n <= 2:
      dense_target = target_matrix.toarray() if sp.issparse(target_matrix) else np.asarray(target_matrix, dtype=float)
      eig_vals, eig_vecs = np.linalg.eig(dense_target)
    else:
      try:
        eig_vals, eig_vecs = spla.eigs(target_matrix, k=1, which="LM")
      except spla.ArpackNoConvergence:
        dense_target = target_matrix.toarray() if sp.issparse(target_matrix) else np.asarray(target_matrix, dtype=float)
        eig_vals, eig_vecs = np.linalg.eig(dense_target)
  else:
    if use_transpose:
      target_matrix = target_dense.T
    else:
      target_matrix = target_dense
    eig_vals, eig_vecs = np.linalg.eig(target_matrix)

  vec = _select_stationary_vector(eig_vals, eig_vecs)
  return normalize(vec)


def _poly_eval(arg, val):
  return np.polyval(arg, val) if isinstance(arg, np.poly1d) else arg


_eval_poly_array = np.frompyfunc(_poly_eval, 2, 1)


def _zero_test(value):
  return value == 0


def _poly_zero_test(poly):
  """Returns true if the polynomial is 0."""
  if isinstance(poly, np.poly1d):
    return poly == np.poly1d([0])
  return poly == 0


_POLY_ZERO = np.poly1d([0])
_POLY_ONE = np.poly1d([1])


def _eliminate_sparse_zeros(matrix: Any) -> Any:
  """Remove explicit zero entries from supported sparse matrix types."""
  if isinstance(matrix, SparseLinearPolyMatrix):
    return matrix.eliminate_zeros()
  if sp.issparse(matrix) and hasattr(matrix, "eliminate_zeros"):
    matrix.eliminate_zeros()
  return matrix


def _ensure_poly1d(value: Any) -> np.poly1d:
  """Return a numpy.poly1d representation for the provided value."""
  if isinstance(value, np.poly1d):
    return value
  if isinstance(value, P):
    return np.poly1d(value.coef)
  if isinstance(value, np.ndarray):
    if value.size == 1:
      return _ensure_poly1d(value.item())
  if isinstance(value, Number):
    return np.poly1d([float(value)])
  if value is None:
    return _POLY_ZERO
  return np.poly1d(value)


def _evaluate_sparse_constant(matrix: Any,
                              eps_value: float = 0.0) -> sp.csr_matrix:
  """Evaluate a (possibly SparseLinearPolyMatrix) sparse polynomial matrix at epsilon."""
  if _is_sparse_poly_matrix(matrix):
    nnz_count = matrix.nnz() if callable(getattr(matrix, "nnz", None)) else int(matrix.nnz)
    if nnz_count == 0:
      return sp.csr_matrix(matrix.shape, dtype=float)

    if isinstance(matrix, SparseLinearPolyMatrix):
      return matrix.evaluate(eps_value)

    rows = []
    cols = []
    data = []
    for (row, col), entry in matrix.items():
      value = float(_ensure_poly1d(entry)(eps_value))
      if value == 0:
        continue
      rows.append(row)
      cols.append(col)
      data.append(value)
    return _eliminate_sparse_zeros(
        sp.csr_matrix((data, (rows, cols)), shape=matrix.shape))

  if matrix.nnz == 0:
    return sp.csr_matrix(matrix.shape, dtype=float)

  coo = matrix.tocoo()
  data = np.empty_like(coo.data, dtype=float)
  for idx, entry in enumerate(coo.data):
    poly = _ensure_poly1d(entry)
    data[idx] = float(poly(eps_value))
  return _eliminate_sparse_zeros(
      sp.csr_matrix((data, (coo.row, coo.col)), shape=matrix.shape))


def _set_sparse_value(matrix: Any,
                      row: int,
                      col: int,
                      value: Any,
                      tol: float = 1e-16):
  """Assign or remove (when value=0) to row, col in a sparse matrix."""
  if _is_sparse_poly_matrix(matrix):
    matrix.set(row, col, value, tol)
    return
  if isinstance(matrix, sp.dok_matrix):
    if _is_zero_poly_entry(value, tol=tol):
      if (row, col) in matrix:
        del matrix[row, col]
    else:
      matrix[row, col] = value
    return
  raise TypeError("Unsupported sparse structure in _set_sparse_value")


def _poly_add(a: Any, b: Any) -> np.poly1d:
  return _ensure_poly1d(a) + _ensure_poly1d(b)


def _poly_sub(a: Any, b: Any) -> np.poly1d:
  return _ensure_poly1d(a) - _ensure_poly1d(b)


def _scale_sparse_linear(matrix: SparseLinearPolyMatrix, scalar: float) -> SparseLinearPolyMatrix:
  result = SparseLinearPolyMatrix(matrix.shape)
  for (row, col), value in matrix.items():
    result.set(row, col, _ensure_poly1d(value) * scalar)
  return result


def _sparse_linear_right_dense_mul(matrix: SparseLinearPolyMatrix,
                                   dense: np.ndarray) -> SparseLinearPolyMatrix:
  """Compute matrix @ dense, preserving sparsity (dense is numeric)."""
  m, k = matrix.shape
  k2, n = dense.shape
  if k != k2:
    raise ValueError("Shape mismatch in _sparse_linear_right_dense_mul")
  result = SparseLinearPolyMatrix((m, n))
  dense_cols = [np.nonzero(dense[row])[0] for row in range(k)]
  for (row, col), value in matrix.items():
    targets = dense_cols[col]
    if targets.size == 0:
      continue
    val_poly = _ensure_poly1d(value)
    for tgt in targets:
      coeff = dense[col, tgt]
      if coeff == 0:
        continue
      existing = result.get((row, tgt), _POLY_ZERO)
      updated = _poly_add(existing, val_poly * coeff)
      result.set(row, tgt, updated)
  return result


def _dense_left_sparse_linear_mul(dense: np.ndarray,
                                  matrix: SparseLinearPolyMatrix) -> SparseLinearPolyMatrix:
  """Compute dense @ matrix, preserving sparsity (dense is numeric)."""
  k, m2 = dense.shape
  m, n = matrix.shape
  if k != m:
    raise ValueError("Shape mismatch in _dense_left_sparse_linear_mul")
  result = SparseLinearPolyMatrix((k, n))
  row_entries = defaultdict(list)
  for (r, c), v in matrix.items():
    row_entries[r].append((c, v))

  for i in range(k):
    nz_cols = np.nonzero(dense[i])[0]
    if nz_cols.size == 0:
      continue
    for row in nz_cols:
      coeff = dense[i, row]
      if coeff == 0:
        continue
      for col, val in row_entries.get(row, []):
        prod = _ensure_poly1d(val) * coeff
        existing = result.get((i, col), _POLY_ZERO)
        result.set(i, col, _poly_add(existing, prod))
  return result


def _sparse_linear_matmul(a: SparseLinearPolyMatrix,
                          b: SparseLinearPolyMatrix) -> SparseLinearPolyMatrix:
  """Compute a @ b for SparseLinearPolyMatrix inputs, keeping sparsity."""
  m, k = a.shape
  k2, n = b.shape
  if k != k2:
    raise ValueError("Shape mismatch in _sparse_linear_matmul")
  result = SparseLinearPolyMatrix((m, n))
  b_rows = defaultdict(list)
  for (row, col), val in b.items():
    b_rows[row].append((col, val))

  for (i, j), aval in a.items():
    if i < 0:
      continue
    if j not in b_rows:
      continue
    aval_poly = _ensure_poly1d(aval)
    for col, bval in b_rows[j]:
      prod = aval_poly * _ensure_poly1d(bval)
      existing = result.get((i, col), _POLY_ZERO)
      updated = _poly_add(existing, prod)
      result.set(i, col, updated)
  return result


def _is_sparse_poly_matrix(matrix: Any) -> bool:
  return isinstance(matrix, SparseLinearPolyMatrix)


def _sparse_poly_indicator(matrix: SparseLinearPolyMatrix) -> sp.csr_matrix:
  """Creates a spare adjacency matrix"""
  rows = []
  cols = []
  for (row, col), value in matrix.items():
    if not _poly_zero_test(value):
      rows.append(row)
      cols.append(col)
  data = np.ones(len(rows), dtype=float)
  return _eliminate_sparse_zeros(
      sp.csr_matrix((data, (rows, cols)), shape=matrix.shape))


def _extract_submatrix(matrix: Any,
                       row_indices: List[int],
                       col_indices: List[int]) -> SparseLinearPolyMatrix:
  """Supports sparse np.ix_ behavior for SparseLinearPolyMatrix inputs."""
  n_rows = len(row_indices)
  n_cols = len(col_indices)
  result = SparseLinearPolyMatrix((n_rows, n_cols))

  row_pos = {row: i for i, row in enumerate(row_indices)}
  col_pos = {col: j for j, col in enumerate(col_indices)}

  if isinstance(matrix, SparseLinearPolyMatrix):
    for (row, col), value in matrix.items():
      if row in row_pos and col in col_pos:
        result.set(row_pos[row], col_pos[col], value)
  elif sp.issparse(matrix):
    coo = matrix.tocoo()
    for r, c, v in zip(coo.row, coo.col, coo.data):
      if r in row_pos and c in col_pos:
        result.set(row_pos[r], col_pos[c], v)
  else:
    raise TypeError("_extract_submatrix expects a sparse input matrix")

  return result


def _make_linear_poly(a0: float, a1: float, tol: float = 1e-14):
  """Returns either the linear polynomial a0 + a1 * eps or just a0 if a1 approx 0."""
  if abs(a1) <= tol:
    return float(a0)
  return np.poly1d([a1, a0])


def _shift_exponent(poly, degree):
  """Lowers the degree of poly."""
  coefs = list(poly.c)
  poly_degree = len(coefs) - 1
  if poly_degree < degree:
    return np.poly1d([])
  del coefs[poly_degree - degree + 1: poly_degree + 1]
  return np.poly1d(coefs)


def _cost_resistance(poly):
  """Return the cost and resistance of poly."""
  poly = _ensure_poly1d(poly)
  coefs = poly.c
  if len(coefs) == 1 and coefs[0] == 0:
    return {"cost": 1, "resistance": "infinity"}
  i = len(coefs) - 1
  while i > 0 and coefs[i] == 0:
    i -= 1
  return {"cost": coefs[i], "resistance": len(coefs) - i - 1}


def _non_uniform_scale(matrix):
  if _is_sparse_poly_matrix(matrix) or sp.issparse(matrix):
    return _non_uniform_scale_sparse(matrix)
  return _non_uniform_scale_dense(matrix)


def _non_uniform_scale_dense(matrix):
  result = {"dim": matrix.shape[1]}
  dim_range = range(result["dim"])
  min_resistance = -1
  max_cost_sum = 0
  non_transient_cols = list(dim_range)

  for col in dim_range:
    min_col_resistance = -1
    col_cost_sum = 0
    for row in dim_range:
      if row == col:
        continue
      cr = _cost_resistance(matrix[row, col])
      if cr["resistance"] == "infinity":
        continue
      if cr["resistance"] == 0:
        min_col_resistance = 0
        break
      if min_col_resistance < 0 or cr["resistance"] < min_col_resistance:
        min_col_resistance = cr["resistance"]
        col_cost_sum = cr["cost"]
      elif cr["resistance"] == min_col_resistance:
        col_cost_sum += cr["cost"]

    if min_col_resistance == 0:
      non_transient_cols.remove(col)
    elif min_col_resistance > 0:
      if min_resistance < 0 or min_col_resistance < min_resistance:
        min_resistance = min_col_resistance
        max_cost_sum = col_cost_sum
      elif min_col_resistance == min_resistance:
        max_cost_sum += col_cost_sum

  if not non_transient_cols:
    raise ValueError("No scaling is possible.")

  result["mat"] = np.array(matrix, copy=True)
  new_mat = result["mat"]
  result["D"] = np.array(np.identity(result["dim"]), dtype=object)
  d_matrix = result["D"]
  del result["dim"]

  f_cost = 2 * max_cost_sum
  if abs(f_cost) <= 1e-16:
    f_cost = 1.0
  tmp = [f_cost]
  tmp.extend([0] * min_resistance)
  scaling_poly = np.poly1d(tmp)
  for col in dim_range:
    if col not in non_transient_cols:
      d_matrix[col, col] = scaling_poly

  poly_one = np.poly1d([1])
  for col in dim_range:
    if col in non_transient_cols:
      for row in dim_range:
        if row == col:
          new_mat[row, col] = poly_one + (poly_one / f_cost) * _shift_exponent(
              matrix[row, col] - poly_one, min_resistance)
        else:
          new_mat[row, col] = (poly_one / f_cost) * _shift_exponent(
              matrix[row, col], min_resistance)
  return result


def _non_uniform_scale_sparse(matrix):
  source = matrix
  dim = source.shape[0]
  column_entries = defaultdict(list)
  for (row, col), value in source.items():
    if row == col:
      continue
    column_entries[col].append((row, value))

  min_resistance = -1
  max_cost_sum = 0
  non_transient_cols = set(range(dim))

  for col in range(dim):
    min_col_resistance = -1
    col_cost_sum = 0
    for row, value in column_entries.get(col, []):
      cr = _cost_resistance(value)
      if cr["resistance"] == "infinity":
        continue
      if cr["resistance"] == 0:
        min_col_resistance = 0
        break
      if min_col_resistance < 0 or cr["resistance"] < min_col_resistance:
        min_col_resistance = cr["resistance"]
        col_cost_sum = cr["cost"]
      elif cr["resistance"] == min_col_resistance:
        col_cost_sum += cr["cost"]

    if min_col_resistance == 0:
      non_transient_cols.discard(col)
    elif min_col_resistance > 0:
      if min_resistance < 0 or min_col_resistance < min_resistance:
        min_resistance = min_col_resistance
        max_cost_sum = col_cost_sum
      elif min_col_resistance == min_resistance:
        max_cost_sum += col_cost_sum

  if not non_transient_cols:
    raise ValueError("No scaling is possible.")

  new_mat = source.copy()
  D = SparseLinearPolyMatrix((dim, dim))
  for i in range(dim):
    D.set(i, i, _POLY_ONE)
  f_cost = 2 * max_cost_sum
  if abs(f_cost) <= 1e-16:
    f_cost = 1.0
  tmp = [f_cost]
  tmp.extend([0] * min_resistance)
  scaling_poly = np.poly1d(tmp)

  for col in range(dim):
    if col not in non_transient_cols:
      D.set(col, col, scaling_poly)
      continue
    diag_orig = _ensure_poly1d(source.get((col, col), _POLY_ZERO))
    diag_new = _POLY_ONE + (_POLY_ONE / f_cost) * _shift_exponent(
        diag_orig - _POLY_ONE, min_resistance)
    _set_sparse_value(new_mat, col, col, diag_new)
    for row, value in column_entries.get(col, []):
      updated = (_POLY_ONE / f_cost) * _shift_exponent(
          _ensure_poly1d(value), min_resistance)
      _set_sparse_value(new_mat, row, col, updated)

  return {
    "mat": new_mat,
    "D": D
  }


def _reduce(matrix, states_to_remove, M0=None):
  """Eliminate selected states from matrix."""
  if _is_sparse_poly_matrix(matrix) or sp.issparse(matrix):
    return _reduce_sparse(matrix, states_to_remove, M0)
  return _reduce_dense(matrix, states_to_remove, M0)


def _reduce_dense(matrix, states_to_remove, M0=None):
  if not states_to_remove:
    raise ValueError("states_to_remove cannot be empty.")

  dim = matrix.shape[1]
  if M0 is None:
    M0 = np.array(_eval_poly_array(matrix, 0), dtype=float)

  complement = list(
      set(range(dim)).symmetric_difference(set(states_to_remove)))
  perm = list(complement)
  perm.extend(states_to_remove)
  P_matrix = np.zeros((dim, dim))
  for col in range(dim):
    P_matrix[perm[col], col] = 1

  Mssbar = matrix[np.ix_(states_to_remove, complement)]
  lambdass_inv = np.linalg.inv(M0[np.ix_(states_to_remove, states_to_remove)] -
                               np.identity(len(states_to_remove)))
  inclusion = P_matrix @ np.block([[np.identity(len(complement))],
                                   [-lambdass_inv @ Mssbar]])
  tmp = matrix[np.ix_(complement, complement)] - matrix[np.ix_(
      complement, states_to_remove)] @ lambdass_inv @ Mssbar

  dim_tmp = tmp.shape[1]
  zero = np.poly1d([0])
  one = np.poly1d([1])
  for col in range(dim_tmp):
    col_sum = zero
    for row in range(dim_tmp):
      if row == col:
        continue
      cr = _cost_resistance(tmp[row, col])
      if cr["resistance"] == "infinity":
        tmp[row, col] = zero
      else:
        coeffs = [0] * (cr["resistance"] + 1)
        coeffs[0] = cr["cost"]
        tmp[row, col] = np.poly1d(coeffs)
      col_sum = col_sum + tmp[row, col]
    tmp[col, col] = one - col_sum

  return {"i": inclusion, "mat": tmp}


def _reduce_sparse(matrix, states_to_remove, M0=None):
  if not states_to_remove:
    raise ValueError("states_to_remove cannot be empty.")

  dim = matrix.shape[1]
  if M0 is None:
    M0 = _evaluate_sparse_constant(matrix, 0)

  complement = list(
      set(range(dim)).symmetric_difference(set(states_to_remove)))
  perm = list(complement)
  perm.extend(states_to_remove)

  Mssbar = _extract_submatrix(matrix, states_to_remove, complement)
  Mbarbar = _extract_submatrix(matrix, complement, complement)
  Mbars = _extract_submatrix(matrix, complement, states_to_remove)

  num_to_remove = len(states_to_remove)
  if num_to_remove == 1:
    # removing a single state is inversion of a scalar.
    s = states_to_remove[0]
    scalar_val = float(M0[s, s]) - 1.0
    lambdass_inv = np.array([[1.0 / scalar_val]], dtype=object)
  else:
    M0_ss = M0[np.ix_(states_to_remove, states_to_remove)]
    if sp.issparse(M0_ss):
      M0_ss = M0_ss.toarray()
    lambdass_inv_numeric = np.linalg.inv(M0_ss - np.identity(num_to_remove))
    lambdass_inv = np.array(lambdass_inv_numeric, dtype=object)

  # Build inclusion matrix
  bottom_block_linear = -_dense_left_sparse_linear_mul(lambdass_inv, Mssbar)
  n_complement = len(complement)
  inclusion = SparseLinearPolyMatrix((dim, n_complement))
  for j in range(n_complement):
    inclusion.set(perm[j], j, _POLY_ONE)
  for (r, c), v in bottom_block_linear.items():
    out_row = perm[n_complement + r]
    inclusion.set(out_row, c, _ensure_poly1d(v))

  prod = (Mbars @ lambdass_inv) @ Mssbar
  tmp = Mbarbar - prod

  dim_tmp = tmp.shape[1]
  zero = np.poly1d([0])
  one = np.poly1d([1])
  for col in range(dim_tmp):
    col_sum = zero
    for row in range(dim_tmp):
      if row == col:
        continue
      current_entry = tmp.get((row, col), _POLY_ZERO)
      cr = _cost_resistance(current_entry)
      if cr["resistance"] != "infinity":
        coeffs = [0] * (cr["resistance"] + 1)
        coeffs[0] = cr["cost"]
        tmp.set(row, col, np.poly1d(coeffs))
      col_sum = col_sum + tmp.get((row, col), _POLY_ZERO)
    tmp.set(col, col, one - col_sum)

  result_matrix = SparseLinearPolyMatrix((dim_tmp, dim_tmp))
  for (row, col), entry in tmp.items():
    if not _poly_zero_test(entry):
      result_matrix.set(row, col, entry)

  return {"i": inclusion, "mat": result_matrix}


def _ssd_step(matrix, reduction_mode: str = "one_by_one"):
  """Performs the next possible reduction step in the SSD algorithm."""
  if reduction_mode not in ("one_by_one", "all_at_once"):
    raise ValueError(
        f"Unknown reduction_mode: {reduction_mode}. "
        "Expected 'one_by_one' or 'all_at_once'.")

  result = {}
  if _is_sparse_poly_matrix(matrix) or sp.issparse(matrix):
    current_matrix = _eliminate_sparse_zeros(matrix)
    inclusion_chain = []

    while True:
      M0 = _evaluate_sparse_constant(current_matrix)
      graph = Graph(M0, _zero_test)
      communicating = graph.CommunicatingClasses()

      if len(communicating) == 1:
        result["stab"] = _stable_distribution(M0)
        if inclusion_chain:
          result["incs"] = inclusion_chain
        return result

      closed = graph.ClosedClasses()

      found_reduction = False
      for cls in closed.values():
        states = list(cls)
        if len(states) > 1:
          if reduction_mode == "all_at_once":
            states_to_remove = states[1:]
          else:
            states_to_remove = [states[0]]

          reduction = _reduce(current_matrix, states_to_remove, M0)
          current_matrix = _eliminate_sparse_zeros(reduction["mat"])
          inclusion_chain.append(_eliminate_sparse_zeros(reduction["i"]))
          found_reduction = True
          break

      if not found_reduction:
        scale_result = _non_uniform_scale(current_matrix)
        scale_result["mat"] = _eliminate_sparse_zeros(scale_result["mat"])
        if inclusion_chain:
          if "D" in scale_result:
            inclusion_chain.append(_eliminate_sparse_zeros(scale_result["D"]))
            del scale_result["D"]
          scale_result["incs"] = inclusion_chain
        elif "D" in scale_result:
          scale_result["D"] = _eliminate_sparse_zeros(scale_result["D"])
        return scale_result

  else:
    M0 = np.array(_eval_poly_array(matrix, 0), dtype=float)

    graph = Graph(M0, _zero_test)
    communicating = graph.CommunicatingClasses()

    if len(communicating) == 1:
      result["stab"] = _stable_distribution(M0)
      return result

    closed = graph.ClosedClasses()
    max_size = 0
    max_class = None
    num_non_trivial = 0
    for cls in closed.values():
      class_len = len(cls)
      if class_len > 1:
        num_non_trivial += 1
      if class_len > max_size:
        max_size = class_len
        max_class = cls

    states = list(max_class)
    if reduction_mode == "all_at_once":
      states_to_remove = states[1:]
    else:
      states_to_remove = [states[0]]
    if num_non_trivial > 0:
      return _reduce(matrix, states_to_remove, M0)

    return _non_uniform_scale(matrix)


def _ssd_iterate(matrix, reduction_mode: str = "one_by_one"):
  """Recursively apply SSD_step until convergence."""
  def _progress_signature(mat):
    if _is_sparse_poly_matrix(mat):
      const_vals = [float(v) for v in mat.constant.values()]
      eps_vals = [float(v) for v in mat.epsilon.values()]
      return (
          "slpm",
          mat.shape,
          len(const_vals),
          len(eps_vals),
          round(float(np.sum(np.abs(const_vals))) if const_vals else 0.0, 12),
          round(float(np.sum(np.abs(eps_vals))) if eps_vals else 0.0, 12),
      )
    if sp.issparse(mat):
      data = np.asarray(mat.data, dtype=float)
      return (
          "sp",
          mat.shape,
          int(mat.nnz),
          round(float(np.sum(np.abs(data))) if data.size else 0.0, 12),
      )
    nnz, total = _matrix_nnz_and_total(mat)
    dense0 = np.array(_eval_poly_array(mat, 0), dtype=float)
    return (
        "dense",
        getattr(mat, "shape", None),
        nnz,
        total,
        round(float(np.sum(np.abs(dense0))) if dense0.size else 0.0, 12),
    )

  transforms = []
  current = matrix
  no_progress_steps = 0

  while True:
    current_sig = _progress_signature(current)
    result = _ssd_step(current, reduction_mode=reduction_mode)
    if "stab" in result:
      vec = result["stab"]
      if "incs" in result:
        for inc in reversed(result["incs"]):
          vec = _eliminate_sparse_zeros(inc) @ vec
      for transform in reversed(transforms):
        if isinstance(transform, list):
          for inc in reversed(transform):
            vec = _eliminate_sparse_zeros(inc) @ vec
        else:
          vec = _eliminate_sparse_zeros(transform) @ vec
      return vec

    if "incs" in result:
      transforms.append(result["incs"])
    elif "i" in result:
      transforms.append(result["i"])
    else:
      transforms.append(result["D"])

    next_matrix = result["mat"]
    next_sig = _progress_signature(next_matrix)
    if next_sig == current_sig:
      no_progress_steps += 1
    else:
      no_progress_steps = 0

    if no_progress_steps >= 3:
      warnings.warn(
          "SSD iteration made no progress for several steps; "
          "falling back to stationary distribution at epsilon=0.")
      base = _evaluate_sparse_constant(next_matrix, 0.0)
      vec = _stable_distribution(base)
      for transform in reversed(transforms):
        if isinstance(transform, list):
          for inc in reversed(transform):
            vec = _eliminate_sparse_zeros(inc) @ vec
        else:
          vec = _eliminate_sparse_zeros(transform) @ vec
      return vec

    current = next_matrix


def _compute_ssd(matrix, reduction_mode: str = "one_by_one"):
  """Computes the SSD of a PMM."""
  if _is_sparse_poly_matrix(matrix):
    graph = Graph(_sparse_poly_indicator(matrix), _zero_test)
  else:
    graph = Graph(matrix, _poly_zero_test)

  graph.CommunicatingClasses()

  stab = _ssd_iterate(matrix, reduction_mode=reduction_mode)

  if sp.issparse(stab):
    vec = np.array(stab.toarray(), dtype=float).flatten()
  else:
    vec = np.array(_eval_poly_array(stab, 0), dtype=float)
  return normalize(vec)


def _is_zero_poly_entry(value,
                        tol: float = 1e-12,
                        ignore_infinitesimal: bool = False) -> bool:
  """Check whether a polynomial matrix entry is approx zero."""
  if value is None:
    return True
  if isinstance(value, np.poly1d):
    if ignore_infinitesimal:
      constant_term = float(value(0.0))
      return abs(constant_term) <= tol
    coeffs = np.asarray(value.coeffs, dtype=float)
    return np.all(np.abs(coeffs) <= tol)
  if isinstance(value, Number):
    return abs(value) <= tol
  try:
    coeffs = np.asarray(value, dtype=float)
    if coeffs.size == 0:
      return True
    return np.all(np.abs(coeffs) <= tol)
  except Exception:
    return False


def _matrix_nnz_and_total(matrix: np.ndarray,
                          tol: float = 1e-12,
                          ignore_infinitesimal: bool = False) -> tuple[int, int]:
  """Returns non-zero count and total entries for a polynomial matrix."""
  if matrix is None:
    return 0, 0
  if _is_sparse_poly_matrix(matrix):
    shape = matrix.shape
    if isinstance(matrix, SparseLinearPolyMatrix):
      constant_keys = set(matrix.constant.keys())
      epsilon_keys = set(matrix.epsilon.keys())
      if ignore_infinitesimal:
        nnz = sum(1 for key in constant_keys if abs(matrix.constant.get(key, 0.0)) > tol)
      else:
        nnz = len(constant_keys | epsilon_keys)
    else:
      if ignore_infinitesimal:
        nnz = 0
        for value in matrix.values():
          if abs(_ensure_poly1d(value)(0.0)) > tol:
            nnz += 1
      else:
        nnz = matrix.nnz()
    return nnz, int(shape[0] * shape[1])
  if sp.issparse(matrix):
    shape = matrix.shape
    return int(matrix.getnnz()), int(shape[0] * shape[1])

  shape = getattr(matrix, "shape", None)
  if shape is None or len(shape) != 2:
    return 0, 0
  total = int(shape[0] * shape[1])

  nnz = 0
  for i, j in np.ndindex(shape):
    entry = matrix[i, j]
    if not _is_zero_poly_entry(entry, tol=tol,
                               ignore_infinitesimal=ignore_infinitesimal):
      nnz += 1
  return nnz, total


def _construct_polynomial_transition_matrix(
        base: Union[np.ndarray, sp.spmatrix],
        perturbation_strength: float,
  use_sparse: bool) -> Union[np.ndarray, sp.spmatrix, SparseLinearPolyMatrix]:
  """Create polynomial transition matrix from a base.
  Here, we use Alpha-Rank's evolutionary dynamics with
  eps = 0 as the base matrix. Then, we add epsilon perturbations
  according to the SSD algorithm and with poly types.
  """
  size = base.shape[0]
  if use_sparse:
    if sp.issparse(base):
      base_sparse = _eliminate_sparse_zeros(
          base.tocsc() if not sp.isspmatrix_csc(base) else base)
    else:
      base_sparse = _eliminate_sparse_zeros(sp.csc_matrix(base))
    matrix = SparseLinearPolyMatrix((size, size))
    for j in range(size):
      noise_target = (j + 1) % size if size > 1 else j
      col_sum = _POLY_ZERO
      processed_rows = set()
      col = base_sparse.getcol(j)
      for idx, row in enumerate(col.indices):
        if row == j:
          continue
        a0 = float(col.data[idx])
        noise_val = 1.0 if row == noise_target else 0.0
        entry = _make_linear_poly(a0,
                                  perturbation_strength * (noise_val - a0))
        if _poly_zero_test(entry):
          continue
        matrix.set(row, j, entry)
        col_sum = col_sum + entry
        processed_rows.add(row)

      if size > 1 and noise_target not in processed_rows and noise_target != j:
        entry = _make_linear_poly(0.0, perturbation_strength)
        if not _poly_zero_test(entry):
          matrix.set(noise_target, j, entry)
          col_sum = col_sum + entry

      matrix.set(j, j, _POLY_ONE - col_sum)

    return matrix

  # Dense case
  matrix = np.zeros((size, size), dtype=object)
  U_val = 1.0 / float(size) if size else 0.0
  for j in range(size):
    for i in range(size):
      a0 = float(base[i, j])
      noise_val = U_val
      a1 = perturbation_strength * (noise_val - a0)
      # base[i, j] + epsilon * (U_val - base[i, j])
      # = (1 - epsilon) * base[i, j] + epsilon * U_val
      entry = _make_linear_poly(a0, a1)
      if isinstance(entry, np.poly1d):
        if _poly_zero_test(entry):
          continue
      elif abs(entry) <= 1e-16:
        continue
      matrix[i, j] = entry

  for j in range(size):
    col_sum = _POLY_ZERO
    for i in range(size):
      if i == j:
        continue
      col_sum = col_sum + _ensure_poly1d(matrix[i, j])
    matrix[j, j] = _POLY_ONE - col_sum

  return matrix


def _construct_perturbed_markov_matrix_ev_dyn(
    payoff_tables: List[Any],
    payoffs_are_hpt_format: bool,
    perturbation_strength: float = 1.0,
    use_sparse: bool = False) -> Union[np.ndarray, sp.spmatrix, SparseLinearPolyMatrix]:
  """Constructs perturbed Markov matrix using evolutionary dynamics."""

  game_info = _convert_alpharank_to_ssd_format(
      payoff_tables, payoffs_are_hpt_format)

  num_populations = game_info["num_populations"]

  m = 10.0
  alpha = 50.0

  if num_populations == 1:
    game_is_constant_sum, payoff_sum = utils.check_is_constant_sum(
        payoff_tables[0], payoffs_are_hpt_format)
    # Use evolutionary dynamics as base with use_inf_alpha False
    c_base, _ = alpharank._get_singlepop_transition_matrix(
        payoff_tables[0], payoffs_are_hpt_format,
        m=m, alpha=alpha,
        game_is_constant_sum=game_is_constant_sum,
        use_local_selection_model=True,
        payoff_sum=payoff_sum,
        use_inf_alpha=False,
        inf_alpha_eps=0.0,
        use_sparse=use_sparse)
    # c_base is a (num_strats x num_strats) matrix with numeric entries.
    base = c_base if sp.issparse(c_base) else np.array(c_base, dtype=float)
  else:
    c_base, _ = alpharank._get_multipop_transition_matrix(
        payoff_tables, payoffs_are_hpt_format,
        m=m, alpha=alpha,
        use_inf_alpha=False,
        inf_alpha_eps=0.0,
        use_sparse=use_sparse)
    base = c_base if sp.issparse(c_base) else np.array(c_base, dtype=float)

  # arank: c[current, next]
  # SSD: M[next, current]
  base = (_eliminate_sparse_zeros(base.transpose())
          if sp.issparse(base) else base.T)

  return _construct_polynomial_transition_matrix(
      base, perturbation_strength, use_sparse)


def compute_ssd(payoff_tables: List[Any],
                perturbation_strength: float = 1,
                verbose: bool = False,
                **kwargs) -> np.ndarray:
  """Compute stochastically stable distribution for given payoff tables.

  Args:
    payoff_tables: List of game payoff tables.
    verbose: Set to True to print intermediate results.
    **kwargs: Additional keyword arguments.
      use_sparse: Whether to use sparse matrices.
      reduction_mode: 'one_by_one' (default) or 'all_at_once' for SSD
        state elimination strategy.

  Returns:
    Stochastically stable distribution as numpy array.
  """
  payoffs_are_hpt_format = utils.check_payoffs_are_hpt(payoff_tables)

  num_strats_per_population = utils.get_num_strats_per_population(
      payoff_tables, payoffs_are_hpt_format)
  if np.array_equal(num_strats_per_population,
                    np.ones(len(num_strats_per_population))):
    rhos = np.asarray([[1]])
    return rhos

  if verbose:
    print("Constructing perturbed Markov matrix")
    print('num_strats_per_population:', num_strats_per_population)

  use_sparse = bool(kwargs.get("use_sparse", False))
  reduction_mode = str(kwargs.get("reduction_mode", "one_by_one")).lower()

  matrix = _construct_perturbed_markov_matrix_ev_dyn(
      payoff_tables, payoffs_are_hpt_format, perturbation_strength,
      use_sparse=use_sparse)

  if verbose:
    print(f"Matrix size: {matrix.shape}")
  nnz, total = _matrix_nnz_and_total(
      matrix, ignore_infinitesimal=use_sparse)
  density = (nnz / total) if total else 0.0
  if verbose and use_sparse:
    density_label = "non inf. density" if use_sparse else "density"
    print("SSD matrix sparsity: {}/{} non-zero entries ({:.2f}% {}).".format(
        nnz, total, density * 100.0, density_label))

  ssd_distribution = _compute_ssd(matrix, reduction_mode=reduction_mode)

  if not _validate_ssd_distribution(ssd_distribution):
    warnings.warn("ssd distribution validation failed, normalizing")
    ssd_distribution = normalize(ssd_distribution)

  return ssd_distribution
