repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: check-symlinks
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: debug-statements
      - id: forbid-new-submodules

  - repo: https://github.com/google/pyink
    rev: 23.12.1 
    hooks:
      - id: pyink
      
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]  # pyink is black-compatible

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: python -m pylint
        language: system  
        types: [python]
        args: ["-rn", "-sn", "--rcfile=.pylintrc"]