//
// Created by Dennis Jöst on 09.04.17.
//

#ifndef DEEPSTACK_CPP_GAMEDEFINITIONS_H
#define DEEPSTACK_CPP_GAMEDEFINITIONS_H

#define DECK_SIZE (MAX_SUITS * MAX_RANKS)

#define MY_MAX_PLAYERS_COUNT 2
#define MY_MAX_HOLE_CARDS 2
#define MY_MAX_BOARD_CARDS 5
#define MY_MAX_ROUNDS 4

#define NUM_ACTIONS_FCPAD 5
#define MAX_HOLE_CARD_COMBINATIONS 1326

#endif //DEEPSTACK_CPP_GAMEDEFINITIONS_H
