FROM mcr.microsoft.com/devcontainers/cpp:0-ubuntu-22.04

# [Optional] Uncomment this section to install additional packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>
