# CMake generated Testfile for 
# Source directory: /home/nierxkrito/open_spiel/open_spiel/games
# Build directory: /home/nierxkrito/open_spiel/open_spiel/python/games
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(2048_test "2048_test")
set_tests_properties(2048_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;288;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(amazons_test "amazons_test")
set_tests_properties(amazons_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;292;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(backgammon_test "backgammon_test")
set_tests_properties(backgammon_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;296;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(bargaining_test "bargaining_test")
set_tests_properties(bargaining_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;302;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(battleship_test "battleship_test")
set_tests_properties(battleship_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;306;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(blackjack_test "blackjack_test")
set_tests_properties(blackjack_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;310;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(blotto_test "blotto_test")
set_tests_properties(blotto_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;314;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(breakthrough_test "breakthrough_test")
set_tests_properties(breakthrough_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;318;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(bridge_test "bridge_test")
set_tests_properties(bridge_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;322;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(catch_test "catch_test")
set_tests_properties(catch_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;326;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(checkers_test "checkers_test")
set_tests_properties(checkers_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;330;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(chess_test "chess_test")
set_tests_properties(chess_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;334;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(cliff_walking_test "cliff_walking_test")
set_tests_properties(cliff_walking_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;338;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(clobber_test "clobber_test")
set_tests_properties(clobber_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;342;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(coin_game_test "coin_game_test")
set_tests_properties(coin_game_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;347;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(colored_trails_test "colored_trails_test")
set_tests_properties(colored_trails_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;355;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(connect_four_test "connect_four_test")
set_tests_properties(connect_four_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;360;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(coop_box_pushing_test "coop_box_pushing_test")
set_tests_properties(coop_box_pushing_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;365;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(coordinated_mp_test "coordinated_mp_test")
set_tests_properties(coordinated_mp_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;370;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(crazy_eights_test "crazy_eights_test")
set_tests_properties(crazy_eights_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;374;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(crowd_modelling_test "crowd_modelling_test")
set_tests_properties(crowd_modelling_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;378;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(crowd_modelling_2d_test "crowd_modelling_2d_test")
set_tests_properties(crowd_modelling_2d_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;382;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(cursor_go_test "cursor_go_test")
set_tests_properties(cursor_go_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;387;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(dark_chess_test "dark_chess_test")
set_tests_properties(dark_chess_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;391;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(dark_hex_test "dark_hex_test")
set_tests_properties(dark_hex_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;395;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(deep_sea_test "deep_sea_test")
set_tests_properties(deep_sea_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;399;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(dots_and_boxes_test "dots_and_boxes_test")
set_tests_properties(dots_and_boxes_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;403;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(dynamic_routing_data_test "dynamic_routing_data_test")
set_tests_properties(dynamic_routing_data_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;407;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(dynamic_routing_test "dynamic_routing_test")
set_tests_properties(dynamic_routing_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;411;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(dynamic_routing_utils_test "dynamic_routing_utils_test")
set_tests_properties(dynamic_routing_utils_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;415;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(dou_dizhu_test "dou_dizhu_test")
set_tests_properties(dou_dizhu_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;419;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(dou_dizhu_utils_test "dou_dizhu_utils_test")
set_tests_properties(dou_dizhu_utils_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;423;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(efg_game_test "efg_game_test")
set_tests_properties(efg_game_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;427;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(einstein_wurfelt_nicht_test "einstein_wurfelt_nicht_test")
set_tests_properties(einstein_wurfelt_nicht_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;431;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(euchre_test "euchre_test")
set_tests_properties(euchre_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;435;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(first_sealed_auction_test "first_sealed_auction_test")
set_tests_properties(first_sealed_auction_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;440;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(garnet_test "garnet_test")
set_tests_properties(garnet_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;444;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(gin_rummy_test "gin_rummy_test")
set_tests_properties(gin_rummy_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;448;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(go_test "go_test")
set_tests_properties(go_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;452;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(phantom_go_test "phantom_go_test")
set_tests_properties(phantom_go_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;456;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(goofspiel_test "goofspiel_test")
set_tests_properties(goofspiel_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;460;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(havannah_test "havannah_test")
set_tests_properties(havannah_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;464;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(hearts_test "hearts_test")
set_tests_properties(hearts_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;468;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(hex_test "hex_test")
set_tests_properties(hex_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;472;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(kriegspiel_test "kriegspiel_test")
set_tests_properties(kriegspiel_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;476;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(kuhn_poker_test "kuhn_poker_test")
set_tests_properties(kuhn_poker_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;481;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(leduc_poker_test "leduc_poker_test")
set_tests_properties(leduc_poker_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;486;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(lewis_signaling_test "lewis_signaling_test")
set_tests_properties(lewis_signaling_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;490;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(liars_dice_test "liars_dice_test")
set_tests_properties(liars_dice_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;495;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(maedn_test "maedn_test")
set_tests_properties(maedn_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;499;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(mancala_test "mancala_test")
set_tests_properties(mancala_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;503;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(markov_soccer_test "markov_soccer_test")
set_tests_properties(markov_soccer_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;508;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(matching_pennies_3p_test "matching_pennies_3p_test")
set_tests_properties(matching_pennies_3p_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;514;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(matrix_games_test "matrix_games_test")
set_tests_properties(matrix_games_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;518;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(mnk_test "mnk_test")
set_tests_properties(mnk_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;522;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(morpion_solitaire_test "morpion_solitaire_test")
set_tests_properties(morpion_solitaire_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;526;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(negotiation_test "negotiation_test")
set_tests_properties(negotiation_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;531;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(nfg_game_test "nfg_game_test")
set_tests_properties(nfg_game_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;536;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(nim_test "nim_test")
set_tests_properties(nim_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;540;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(nine_mens_morris_test "nine_mens_morris_test")
set_tests_properties(nine_mens_morris_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;544;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(oh_hell_test "oh_hell_test")
set_tests_properties(oh_hell_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;548;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(oshi_zumo_test "oshi_zumo_test")
set_tests_properties(oshi_zumo_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;553;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(othello_test "othello_test")
set_tests_properties(othello_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;557;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(oware_test "oware_test")
set_tests_properties(oware_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;562;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(pathfinding_test "pathfinding_test")
set_tests_properties(pathfinding_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;566;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(pentago_test "pentago_test")
set_tests_properties(pentago_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;570;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(phantom_ttt_test "phantom_ttt_test")
set_tests_properties(phantom_ttt_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;574;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(pig_test "pig_test")
set_tests_properties(pig_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;578;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(quoridor_test "quoridor_test")
set_tests_properties(quoridor_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;582;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(rbc_test "rbc_test")
set_tests_properties(rbc_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;586;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(sheriff_test "sheriff_test")
set_tests_properties(sheriff_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;590;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(skat_test "skat_test")
set_tests_properties(skat_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;594;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(solitaire_test "solitaire_test")
set_tests_properties(solitaire_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;598;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(spades_test "spades_test")
set_tests_properties(spades_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;602;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(stones_and_gems_test "stones_and_gems_test")
set_tests_properties(stones_and_gems_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;607;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(tarok_test "tarok_test")
set_tests_properties(tarok_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;611;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(tic_tac_toe_test "tic_tac_toe_test")
set_tests_properties(tic_tac_toe_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;615;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(laser_tag_test "laser_tag_test")
set_tests_properties(laser_tag_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;619;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(tiny_bridge_test "tiny_bridge_test")
set_tests_properties(tiny_bridge_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;624;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(tiny_hanabi_test "tiny_hanabi_test")
set_tests_properties(tiny_hanabi_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;629;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(trade_comm_test "trade_comm_test")
set_tests_properties(trade_comm_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;633;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(twixt_test "twixt_test")
set_tests_properties(twixt_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;637;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(ultimate_tic_tac_toe_test "ultimate_tic_tac_toe_test")
set_tests_properties(ultimate_tic_tac_toe_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;641;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(y_test "y_test")
set_tests_properties(y_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;653;add_test;/home/nierxkrito/open_spiel/open_spiel/games/CMakeLists.txt;0;")
