# CMake generated Testfile for 
# Source directory: /home/nierxkrito/open_spiel/open_spiel/algorithms
# Build directory: /home/nierxkrito/open_spiel/open_spiel/python/algorithms
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(best_response_test "best_response_test")
set_tests_properties(best_response_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/algorithms/CMakeLists.txt;89;add_test;/home/nierxkrito/open_spiel/open_spiel/algorithms/CMakeLists.txt;0;")
add_test(cfr_test "cfr_test")
set_tests_properties(cfr_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/algorithms/CMakeLists.txt;93;add_test;/home/nierxkrito/open_spiel/open_spiel/algorithms/CMakeLists.txt;0;")
add_test(cfr_br_test "cfr_br_test")
set_tests_properties(cfr_br_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/algorithms/CMakeLists.txt;97;add_test;/home/nierxkrito/open_spiel/open_spiel/algorithms/CMakeLists.txt;0;")
add_test(corr_dist_test "corr_dist_test")
set_tests_properties(corr_dist_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/algorithms/CMakeLists.txt;101;add_test;/home/nierxkrito/open_spiel/open_spiel/algorithms/CMakeLists.txt;0;")
add_test(corr_dev_builder_test "corr_dev_builder_test")
set_tests_properties(corr_dev_builder_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/algorithms/CMakeLists.txt;105;add_test;/home/nierxkrito/open_spiel/open_spiel/algorithms/CMakeLists.txt;0;")
add_test(deterministic_policy_test "deterministic_policy_test")
set_tests_properties(deterministic_policy_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/algorithms/CMakeLists.txt;109;add_test;/home/nierxkrito/open_spiel/open_spiel/algorithms/CMakeLists.txt;0;")
add_test(evaluate_bots_test "evaluate_bots_test")
set_tests_properties(evaluate_bots_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/algorithms/CMakeLists.txt;113;add_test;/home/nierxkrito/open_spiel/open_spiel/algorithms/CMakeLists.txt;0;")
add_test(external_sampling_mccfr_test "external_sampling_mccfr_test")
set_tests_properties(external_sampling_mccfr_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/algorithms/CMakeLists.txt;117;add_test;/home/nierxkrito/open_spiel/open_spiel/algorithms/CMakeLists.txt;0;")
add_test(get_all_histories_test "get_all_histories_test")
set_tests_properties(get_all_histories_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/algorithms/CMakeLists.txt;121;add_test;/home/nierxkrito/open_spiel/open_spiel/algorithms/CMakeLists.txt;0;")
add_test(get_all_states_test "get_all_states_test")
set_tests_properties(get_all_states_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/algorithms/CMakeLists.txt;125;add_test;/home/nierxkrito/open_spiel/open_spiel/algorithms/CMakeLists.txt;0;")
add_test(get_legal_actions_map_test "get_legal_actions_map_test")
set_tests_properties(get_legal_actions_map_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/algorithms/CMakeLists.txt;129;add_test;/home/nierxkrito/open_spiel/open_spiel/algorithms/CMakeLists.txt;0;")
add_test(history_tree_test "history_tree_test")
set_tests_properties(history_tree_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/algorithms/CMakeLists.txt;133;add_test;/home/nierxkrito/open_spiel/open_spiel/algorithms/CMakeLists.txt;0;")
add_test(infostate_tree_test "infostate_tree_test")
set_tests_properties(infostate_tree_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/algorithms/CMakeLists.txt;137;add_test;/home/nierxkrito/open_spiel/open_spiel/algorithms/CMakeLists.txt;0;")
add_test(is_mcts_test "is_mcts_test")
set_tests_properties(is_mcts_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/algorithms/CMakeLists.txt;141;add_test;/home/nierxkrito/open_spiel/open_spiel/algorithms/CMakeLists.txt;0;")
add_test(matrix_game_utils_test "matrix_game_utils_test")
set_tests_properties(matrix_game_utils_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/algorithms/CMakeLists.txt;145;add_test;/home/nierxkrito/open_spiel/open_spiel/algorithms/CMakeLists.txt;0;")
add_test(minimax_test "minimax_test")
set_tests_properties(minimax_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/algorithms/CMakeLists.txt;149;add_test;/home/nierxkrito/open_spiel/open_spiel/algorithms/CMakeLists.txt;0;")
add_test(observation_history_test "observation_history_test")
set_tests_properties(observation_history_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/algorithms/CMakeLists.txt;153;add_test;/home/nierxkrito/open_spiel/open_spiel/algorithms/CMakeLists.txt;0;")
add_test(oos_test "oos_test")
set_tests_properties(oos_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/algorithms/CMakeLists.txt;157;add_test;/home/nierxkrito/open_spiel/open_spiel/algorithms/CMakeLists.txt;0;")
add_test(outcome_sampling_mccfr_test "outcome_sampling_mccfr_test")
set_tests_properties(outcome_sampling_mccfr_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/algorithms/CMakeLists.txt;161;add_test;/home/nierxkrito/open_spiel/open_spiel/algorithms/CMakeLists.txt;0;")
add_test(state_distribution_test "state_distribution_test")
set_tests_properties(state_distribution_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/algorithms/CMakeLists.txt;165;add_test;/home/nierxkrito/open_spiel/open_spiel/algorithms/CMakeLists.txt;0;")
add_test(tabular_best_response_mdp_test "tabular_best_response_mdp_test")
set_tests_properties(tabular_best_response_mdp_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/algorithms/CMakeLists.txt;169;add_test;/home/nierxkrito/open_spiel/open_spiel/algorithms/CMakeLists.txt;0;")
add_test(tabular_exploitability_test "tabular_exploitability_test")
set_tests_properties(tabular_exploitability_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/algorithms/CMakeLists.txt;173;add_test;/home/nierxkrito/open_spiel/open_spiel/algorithms/CMakeLists.txt;0;")
add_test(tabular_sarsa_test "tabular_sarsa_test")
set_tests_properties(tabular_sarsa_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/algorithms/CMakeLists.txt;177;add_test;/home/nierxkrito/open_spiel/open_spiel/algorithms/CMakeLists.txt;0;")
add_test(tabular_q_learning_test "tabular_q_learning_test")
set_tests_properties(tabular_q_learning_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/algorithms/CMakeLists.txt;181;add_test;/home/nierxkrito/open_spiel/open_spiel/algorithms/CMakeLists.txt;0;")
add_test(tensor_game_utils_test "tensor_game_utils_test")
set_tests_properties(tensor_game_utils_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/algorithms/CMakeLists.txt;185;add_test;/home/nierxkrito/open_spiel/open_spiel/algorithms/CMakeLists.txt;0;")
add_test(trajectories_test "trajectories_test")
set_tests_properties(trajectories_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nierxkrito/open_spiel/open_spiel/algorithms/CMakeLists.txt;189;add_test;/home/nierxkrito/open_spiel/open_spiel/algorithms/CMakeLists.txt;0;")
subdirs("alpha_zero_torch")
subdirs("dqn_torch")
